/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as aggregatorSol from "./aggregator.sol";
export type { aggregatorSol };
import type * as swapSol from "./swap.sol";
export type { swapSol };
import type * as swapaggSol from "./swapagg.sol";
export type { swapaggSol };
