/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface OneInchSwapperInterface extends utils.Interface {
  functions: {
    "inToken()": FunctionFragment;
    "oneInch()": FunctionFragment;
    "outToken()": FunctionFragment;
    "swapTokens(uint256,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "inToken" | "oneInch" | "outToken" | "swapTokens"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "inToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "oneInch", values?: undefined): string;
  encodeFunctionData(functionFragment: "outToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "swapTokens",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(functionFragment: "inToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "oneInch", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "outToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "swapTokens", data: BytesLike): Result;

  events: {};
}

export interface OneInchSwapper extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: OneInchSwapperInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    inToken(overrides?: CallOverrides): Promise<[string]>;

    oneInch(overrides?: CallOverrides): Promise<[string]>;

    outToken(overrides?: CallOverrides): Promise<[string]>;

    swapTokens(
      amountIn: PromiseOrValue<BigNumberish>,
      maxSlippage: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  inToken(overrides?: CallOverrides): Promise<string>;

  oneInch(overrides?: CallOverrides): Promise<string>;

  outToken(overrides?: CallOverrides): Promise<string>;

  swapTokens(
    amountIn: PromiseOrValue<BigNumberish>,
    maxSlippage: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    inToken(overrides?: CallOverrides): Promise<string>;

    oneInch(overrides?: CallOverrides): Promise<string>;

    outToken(overrides?: CallOverrides): Promise<string>;

    swapTokens(
      amountIn: PromiseOrValue<BigNumberish>,
      maxSlippage: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    inToken(overrides?: CallOverrides): Promise<BigNumber>;

    oneInch(overrides?: CallOverrides): Promise<BigNumber>;

    outToken(overrides?: CallOverrides): Promise<BigNumber>;

    swapTokens(
      amountIn: PromiseOrValue<BigNumberish>,
      maxSlippage: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    inToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    oneInch(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    outToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    swapTokens(
      amountIn: PromiseOrValue<BigNumberish>,
      maxSlippage: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
