/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IOneSplit,
  IOneSplitInterface,
} from "../../../contracts/aggregator.sol/IOneSplit";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "fromToken",
        type: "address",
      },
      {
        internalType: "address",
        name: "destToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "parts",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "flags",
        type: "uint256",
      },
    ],
    name: "getExpectedReturn",
    outputs: [
      {
        internalType: "uint256",
        name: "returnAmount",
        type: "uint256",
      },
      {
        internalType: "uint256[]",
        name: "distribution",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IOneSplit__factory {
  static readonly abi = _abi;
  static createInterface(): IOneSplitInterface {
    return new utils.Interface(_abi) as IOneSplitInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IOneSplit {
    return new Contract(address, _abi, signerOrProvider) as IOneSplit;
  }
}
